update

diff --git a/zsh/.config/zsh/funcs b/zsh/.config/zsh/funcs
--- a/zsh/.config/zsh/funcs
+++ b/zsh/.config/zsh/funcs
@@ -2,115 +2,115 @@
 
 # Create a new directory and enter it
 function mkd() {
-	mkdir -p "$@" && cd "$_";
+	mkdir -p "$@" && cd "$_"
 }
 
 validateYaml() {
-    # TODO: Need to export ? yaml built in module? py2 ?
-    export PYENV_VERSION=3.8.13 && pyenv exec python -c 'import yaml,sys;yaml.safe_load(sys.stdin)' < $1
+	# TODO: Need to export ? yaml built in module? py2 ?
+	export PYENV_VERSION=3.8.13 && pyenv exec python -c 'import yaml,sys;yaml.safe_load(sys.stdin)' <$1
 }
 
 cat1Line() {
-    cat $1 | tr -d "\n"
+	cat $1 | tr -d "\n"
 }
 
 eslintify() {
-    cat $1 > /tmp/file_to_eslint
-    npx eslint
+	cat $1 >/tmp/file_to_eslint
+	npx eslint
 }
 
 startMongo() {
-    sudo systemctl start mongod
-    sudo systemctl enable mongod
+	sudo systemctl start mongod
+	sudo systemctl enable mongod
 }
 
 # Create a data URL from a file
 function dataurl() {
-	local mimeType=$(file -b --mime-type "$1");
+	local mimeType=$(file -b --mime-type "$1")
 	if [[ $mimeType == text/* ]]; then
-		mimeType="${mimeType};charset=utf-8";
+		mimeType="${mimeType};charset=utf-8"
 	fi
-	echo "data:${mimeType};base64,$(openssl base64 -in "$1" | tr -d '\n')";
+	echo "data:${mimeType};base64,$(openssl base64 -in "$1" | tr -d '\n')"
 }
 
 # python2 removed - set up for python3
 # Start an HTTP server from a directory, optionally specifying the port
 function server() {
-	local port="${1:-8000}";
+	local port="${1:-8000}"
 	sleep 1 && open "http://localhost:${port}/" &
 	# Set the default Content-Type to `text/plain` instead of `application/octet-stream`
 	# And serve everything as UTF-8 (although not technically correct, this doesn’t break anything for binary files)
 
-    # python
+	# python
 	# python -c $'import SimpleHTTPServer;\nmap = SimpleHTTPServer.SimpleHTTPRequestHandler.extensions_map;\nmap[""] = "text/plain";\nfor key, value in map.items():\n\tmap[key] = value + ";charset=UTF-8";\nSimpleHTTPServer.test();' "$port";
 
-    # python3
-    # https://stackabuse.com/serving-files-with-pythons-simplehttpserver-module/
-    # python3 -c $'import http.server;\nimport socketserver;\nimport sys;\nPORT = int(sys.argv[1]);\nhandler = http.server.SimpleHTTPRequestHandler;\nmap = handler.extensions_map;\nmap[""] = "text/plain";\nfor key, value in map.items():\n\tmap[key] = value + ";charset=UTF-8";\nwith socketserver.TCPServer(("", PORT), handler) as httpd:\n\thttpd.serve_forever();' "$port";
+	# python3
+	# https://stackabuse.com/serving-files-with-pythons-simplehttpserver-module/
+	# python3 -c $'import http.server;\nimport socketserver;\nimport sys;\nPORT = int(sys.argv[1]);\nhandler = http.server.SimpleHTTPRequestHandler;\nmap = handler.extensions_map;\nmap[""] = "text/plain";\nfor key, value in map.items():\n\tmap[key] = value + ";charset=UTF-8";\nwith socketserver.TCPServer(("", PORT), handler) as httpd:\n\thttpd.serve_forever();' "$port";
 
-    # use pyenv
-    export PYENV_VERSION=3.8.13 && pyenv exec python -c $'from http.server import test, SimpleHTTPRequestHandler as RH; import sys; RH.extensions_map[""] = "text/plain"; RH.extensions_map={k:v+";charset=UTF-8" for k,v in RH.extensions_map.items()}; test(RH, port=int(sys.argv[1]));' "$port";
+	# use pyenv
+	export PYENV_VERSION=3.8.13 && pyenv exec python -c $'from http.server import test, SimpleHTTPRequestHandler as RH; import sys; RH.extensions_map[""] = "text/plain"; RH.extensions_map={k:v+";charset=UTF-8" for k,v in RH.extensions_map.items()}; test(RH, port=int(sys.argv[1]));' "$port"
 
 }
 
 increaseWatchers() {
-    sudo sysctl fs.inotify.max_user_watches=65536
-    sudo sysctl -p
+	sudo sysctl fs.inotify.max_user_watches=65536
+	sudo sysctl -p
 }
 
 change_background() {
-    dconf write /org/mate/desktop/background/picture-filename "'$HOME/dotfiles/backgrounds/$(ls ~/dotfiles/backgrounds | fzf)'"
+	dconf write /org/mate/desktop/background/picture-filename "'$HOME/dotfiles/backgrounds/$(ls ~/dotfiles/backgrounds | fzf)'"
 }
 
-die () {
-    echo >&2 "$@"
-    exit 1
+die() {
+	echo >&2 "$@"
+	exit 1
 }
 
-extract () {
-     if [ -f $1 ] ; then
-         case $1 in
-             *.tar.bz2)   tar xjf $1        ;;
-             *.tar.gz)    tar xzf $1     ;;
-             *.bz2)       bunzip2 $1       ;;
-             *.rar)       rar x $1     ;;
-             *.gz)        gunzip $1     ;;
-             *.tar)       tar xf $1        ;;
-             *.tbz2)      tar xjf $1      ;;
-             *.tgz)       tar xzf $1       ;;
-             *.zip)       unzip $1     ;;
-             *.Z)         uncompress $1  ;;
-             *.7z)        7z x $1    ;;
-             *.xz)        unxz $1   ;;
-             *)           echo "'$1' cannot be extracted via extract()" ;;
-         esac
-     else
-         echo "'$1' is not a valid file"
-     fi
+extract() {
+	if [ -f $1 ]; then
+		case $1 in
+		*.tar.bz2) tar xjf $1 ;;
+		*.tar.gz) tar xzf $1 ;;
+		*.bz2) bunzip2 $1 ;;
+		*.rar) rar x $1 ;;
+		*.gz) gunzip $1 ;;
+		*.tar) tar xf $1 ;;
+		*.tbz2) tar xjf $1 ;;
+		*.tgz) tar xzf $1 ;;
+		*.zip) unzip $1 ;;
+		*.Z) uncompress $1 ;;
+		*.7z) 7z x $1 ;;
+		*.xz) unxz $1 ;;
+		*) echo "'$1' cannot be extracted via extract()" ;;
+		esac
+	else
+		echo "'$1' is not a valid file"
+	fi
 }
 
 # Determine size of a file or total size of a directory
 function fs() {
-	if du -b /dev/null > /dev/null 2>&1; then
-		local arg=-sbh;
+	if du -b /dev/null >/dev/null 2>&1; then
+		local arg=-sbh
 	else
-		local arg=-sh;
+		local arg=-sh
 	fi
 	if [[ -n "$@" ]]; then
-		du $arg -- "$@";
+		du $arg -- "$@"
 	else
-		du $arg .[^.]* ./*;
-	fi;
+		du $arg .[^.]* ./*
+	fi
 }
 
 # `o` with no arguments opens the current directory, otherwise opens the given
 # location
 function o() {
 	if [ $# -eq 0 ]; then
-		open .;
+		open .
 	else
-		open "$@";
-	fi;
+		open "$@"
+	fi
 }
 
 # This script was automatically generated by the broot program
@@ -120,25 +120,18 @@ function o() {
 # It's needed because some shell commands, like `cd`,
 # have no useful effect if executed in a subshell.
 function br {
-    local cmd cmd_file code
-    cmd_file=$(mktemp)
-    if broot --outcmd "$cmd_file" "$@"; then
-        cmd=$(<"$cmd_file")
-        rm -f "$cmd_file"
-        eval "$cmd"
-    else
-        code=$?
-        rm -f "$cmd_file"
-        return "$code"
-    fi
+	local cmd cmd_file code
+	cmd_file=$(mktemp)
+	if broot --outcmd "$cmd_file" "$@"; then
+		cmd=$(<"$cmd_file")
+		rm -f "$cmd_file"
+		eval "$cmd"
+	else
+		code=$?
+		rm -f "$cmd_file"
+		return "$code"
+	fi
 }
-
-# fuck
-eval $(thefuck --alias)
-# You can use whatever you want as an alias, like for Mondays:
-# eval $(thefuck --alias FUCK)
-
-
 
 # STILLS
 # This function uses ffmpeg.
@@ -194,7 +187,7 @@ make_gif() {
 # $3 is the duration of the gif in seconds.
 # $4 is the gif file name.
 get_gif() {
-	pre_gif "$1" "$2" "$3" "$4";
-	make_gif "$4";
-	rm "$4".mp4;
+	pre_gif "$1" "$2" "$3" "$4"
+	make_gif "$4"
+	rm "$4".mp4
 }
